"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import PostCard from "@/components/post/PostCard";
import ReportQueue from "@/components/admin/ReportQueue";
import { createGroupPost, decideGroupJoin, fetchGroupJoinRequests, fetchGroupMembers, fetchGroupPosts, fetchGroups, fetchMyGroupPosts, fetchPendingGroupPosts, kickGroupMember, leaveGroup, moderateGroupPost, requestGroupJoin, setGroupPostPinned } from "@/lib/api";
import { getAuthUser } from "@/lib/auth";
import { safeImageSrc } from "@/lib/media";
import type { ApiGroup, GroupJoinRequest, GroupMember, GroupPost } from "@/types/group-api";
import { useDialog } from "@/components/ui/DialogProvider";
import RelativeTime from "@/components/ui/RelativeTime";

const order = ["pass-do", "ghep-phong-tim-tro", "su-kien", "hoc-tap"];
const icons: Record<string, string> = { "pass-do": "🛍️", "ghep-phong-tim-tro": "🏠", "su-kien": "📅", "hoc-tap": "📚" };

export default function GroupsPage() {
  const dialog = useDialog(); const searchParams = useSearchParams(); const requestedGroupId = searchParams.get("group");
  const [groups, setGroups] = useState<ApiGroup[]>([]), [activeId, setActiveId] = useState(""), [posts, setPosts] = useState<GroupPost[]>([]), [myPosts, setMyPosts] = useState<GroupPost[]>([]), [pending, setPending] = useState<GroupPost[]>([]), [requests, setRequests] = useState<GroupJoinRequest[]>([]), [members, setMembers] = useState<GroupMember[]>([]);
  const [tab, setTab] = useState<"posts" | "requests" | "members">("posts"), [content, setContent] = useState(""), [files, setFiles] = useState<File[]>([]), [query, setQuery] = useState(""), [sort, setSort] = useState<"latest" | "featured" | "pinned">("latest"), [showMine, setShowMine] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [auth, setAuth] = useState<ReturnType<typeof getAuthUser>>(null);
  const active = groups.find(group => group.id === activeId);
  const isAdmin = !!active && (auth?.system_role === "SUPER_ADMIN" || auth?.admin_group_slugs?.includes(active.slug));
  const canPost = !!active && (active.membership === "MEMBER" || active.membership === "ADMIN" || auth?.system_role === "SUPER_ADMIN");
  const canRead = canPost;
  const loadGroups = useCallback(async () => { const rows = await fetchGroups(); rows.sort((a, b) => order.indexOf(a.slug) - order.indexOf(b.slug)); setGroups(rows); setActiveId(value => rows.some(group => group.id === requestedGroupId) ? (requestedGroupId || "") : (value || rows.find(group => order.includes(group.slug))?.id || "")); }, [requestedGroupId]);
  const load = useCallback(async () => { if (!activeId) return; const selected = groups.find(group => group.id === activeId); const admin = !!selected && (auth?.system_role === "SUPER_ADMIN" || auth?.admin_group_slugs?.includes(selected.slug)); if (!selected || (!admin && !["MEMBER", "ADMIN"].includes(selected.membership))) { setPosts([]); setMyPosts([]); setPending([]); setRequests([]); setMembers([]); return; } const [feed, mine] = await Promise.all([fetchGroupPosts(activeId, query, sort), fetchMyGroupPosts(activeId)]); setPosts(feed); setMyPosts(mine); if (admin) { const [pendingPosts, joinRequests, groupMembers] = await Promise.all([fetchPendingGroupPosts(activeId), fetchGroupJoinRequests(activeId), fetchGroupMembers(activeId)]); setPending(pendingPosts); setRequests(joinRequests); setMembers(groupMembers); } else { setPending([]); setRequests([]); setMembers([]); } }, [activeId, groups, auth, query, sort]);
  useEffect(() => { setAuth(getAuthUser()); void loadGroups().catch(error => setError(error.message)); }, [loadGroups]);
  useEffect(() => { void load().catch(error => setError(error.message)); }, [load]);
  const act = async (work: () => Promise<unknown>) => { setBusy(true); setError(""); try { await work(); await loadGroups(); await load(); } catch (error) { setError(error instanceof Error ? error.message : "Có lỗi xảy ra."); } finally { setBusy(false); } };
  const submit = () => act(async () => { if (!active || (!content.trim() && !files.length)) return; await createGroupPost(active.id, content.trim(), files); setContent(""); setFiles([]); setShowMine(true); });
  const rejectPost = async (post: GroupPost) => { if (!active) return; const reason = await dialog.prompt({ title: "Từ chối bài viết", message: `Nêu lý do để ${post.author.name} biết cách chỉnh sửa.`, placeholder: "Lý do từ chối...", multiline: true, minLength: 3, tone: "danger" }); if (reason) await act(() => moderateGroupPost(active.id, post.id, "REJECT", reason)); };
  const kickMember = async (member: GroupMember) => { if (!active) return; if (await dialog.confirm({ title: "Mời thành viên khỏi nhóm?", message: `${member.name} sẽ mất quyền truy cập nội dung dành cho thành viên.`, confirmLabel: "Mời khỏi nhóm", tone: "danger" })) await act(() => kickGroupMember(active.id, member.id)); };
  return <main className="live-groups-page">
    <section className="live-groups-hero"><span>CỘNG ĐỒNG HVNH</span><h1>Bốn không gian dành cho sinh viên</h1><p>Tham gia nhóm, chia sẻ nội dung và theo dõi kết quả kiểm duyệt minh bạch.</p></section>
    <nav className="live-group-tabs">{groups.filter(group => order.includes(group.slug)).map(group => <button key={group.id} className={group.id === activeId ? "active" : ""} onClick={() => { setActiveId(group.id); setQuery(""); setShowMine(false); }}><b>{icons[group.slug]} {group.name}</b><small>{group.member_count} thành viên</small></button>)}</nav>
    {active && <>
      <section className="live-group-summary"><div><h2>{icons[active.slug]} {active.name}</h2><p>{active.description}</p></div><div>{isAdmin && <Link className="group-admin-entry" href={`/group-admin?groupId=${active.id}`}>Mở trung tâm quản trị</Link>}{active.membership === "NONE" && <button disabled={busy} onClick={() => act(() => requestGroupJoin(active.id))}>Tham gia nhóm</button>}{active.membership === "PENDING" && <button disabled>Đang chờ duyệt</button>}{active.membership === "MEMBER" && <button disabled={busy} className="secondary" onClick={() => act(() => leaveGroup(active.id))}>Rời nhóm</button>}{active.membership === "ADMIN" && <span className="live-admin-badge">Group Admin</span>}</div></section>
      {canPost && <section className="live-group-composer group-facebook-composer"><div className="group-composer-author"><img src={safeImageSrc(auth?.avatar_url)} alt=""/><div><strong>{auth?.full_name || "Sinh viên HVNH"}</strong><span>Đăng trong <b>{active.name}</b> · Bài viết sẽ được duyệt trước khi hiển thị</span></div></div><textarea value={content} onChange={event => setContent(event.target.value)} placeholder={`Bạn muốn chia sẻ điều gì với ${active.name}?`} /><div className="group-composer-footer"><label className="group-file-action"><input type="file" multiple accept="image/*,video/*,audio/*,application/pdf,text/plain,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.zip" onChange={event => setFiles(Array.from(event.target.files || []))}/><span>🖼️ Ảnh / Video / Tệp</span></label><button disabled={busy || (!content.trim() && !files.length)} onClick={submit}>{busy ? "Đang gửi..." : "Đăng bài"}</button></div>{!!files.length && <small className="group-selected-files">Đã chọn {files.length} tệp đính kèm.</small>}</section>}
      {isAdmin && <section className="live-admin-panel"><header><div><span>TRUNG TÂM KIỂM DUYỆT</span><h2>Quản trị {active.name}</h2></div><nav><button className={tab === "posts" ? "active" : ""} onClick={() => setTab("posts")}>Bài chờ ({pending.length})</button><button className={tab === "requests" ? "active" : ""} onClick={() => setTab("requests")}>Xin vào nhóm ({requests.length})</button><button className={tab === "members" ? "active" : ""} onClick={() => setTab("members")}>Thành viên ({members.length})</button></nav></header><div className="live-admin-list">{tab === "posts" && pending.map(post => <article key={post.id}><div><strong>{post.author.name}</strong><p>{post.content || "Bài viết chỉ có media"}</p></div><div><button onClick={() => act(() => moderateGroupPost(active.id, post.id, "APPROVE"))}>Phê duyệt</button><button className="danger" onClick={() => void rejectPost(post)}>Từ chối</button></div></article>)}{tab === "requests" && requests.map(request => <article key={request.id}><div><strong>{request.name}</strong><p>@{request.username}</p></div><div><button onClick={() => act(() => decideGroupJoin(active.id, request.id, "APPROVE"))}>Chấp nhận</button><button className="danger" onClick={() => act(() => decideGroupJoin(active.id, request.id, "REJECT"))}>Từ chối</button></div></article>)}{tab === "members" && members.map(member => <article key={member.id}><div><strong>{member.name}</strong><p>{member.student_code || member.username} · {member.role}</p></div>{member.role === "MEMBER" && <button className="danger" onClick={() => void kickMember(member)}>Mời khỏi nhóm</button>}</article>)}{((tab === "posts" && !pending.length) || (tab === "requests" && !requests.length) || (tab === "members" && !members.length)) && <p className="live-empty">Chưa có dữ liệu.</p>}</div></section>}
      {canRead ? <><section className="group-user-tools"><div className="group-feed-filters"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Tìm trong nhóm…"/><select value={sort} onChange={event => setSort(event.target.value as typeof sort)}><option value="latest">Mới nhất</option><option value="featured">Nổi bật</option><option value="pinned">Đã ghim</option></select><button className={showMine ? "active" : "secondary"} onClick={() => setShowMine(value => !value)}>Bài của tôi ({myPosts.length})</button></div>{showMine && <div className="my-group-posts"><h3>Trạng thái bài đã gửi</h3>{myPosts.map(post => <article key={post.id}><div><b className={`post-status ${post.status.toLowerCase()}`}>{post.status === "PENDING" ? "Chờ duyệt" : post.status === "APPROVED" ? "Đã duyệt" : "Bị từ chối"}</b><RelativeTime value={post.createdAt}/></div><p>{post.content || "Bài viết chỉ có media"}</p>{post.rejectionReason && <strong>Lý do: {post.rejectionReason}</strong>}</article>)}{!myPosts.length && <p className="live-empty">Bạn chưa gửi bài nào trong nhóm này.</p>}</div>}</section><section className="live-group-feed"><header><h2>Bài viết trong nhóm</h2><span>{posts.length} bài phù hợp</span></header>{posts.map(post => <div key={post.id} className="live-post-wrap">{post.isPinned && <span className="live-pin-label">📌 Bài viết đã ghim</span>}<PostCard post={post}/>{isAdmin && <button className="live-pin-button" onClick={() => act(() => setGroupPostPinned(active.id, post.id, !post.isPinned))}>{post.isPinned ? "Bỏ ghim" : "Ghim bài"}</button>}</div>)}{!posts.length && <div className="live-empty-card">Không có bài viết phù hợp với bộ lọc.</div>}</section></> : <section className="group-join-gate"><span aria-hidden="true">🔒</span><h2>Tham gia {active.name} để xem bài viết</h2><p>Chỉ thành viên mới xem, thích và bình luận bài trong nhóm. Quản trị viên sẽ duyệt yêu cầu tham gia của bạn.</p>{active.membership === "NONE" && <button type="button" disabled={busy} onClick={() => act(() => requestGroupJoin(active.id))}>Gửi yêu cầu tham gia</button>}{active.membership === "PENDING" && <strong>Yêu cầu của bạn đang chờ duyệt</strong>}</section>}
    </>}{error && <div className="live-group-error">{error}</div>}{isAdmin && active && <ReportQueue groupId={active.id}/>}</main>;
}
