"use client";
import {useEffect,useState} from "react";
import {createReport,deletePost,editPost} from "@/lib/api";
import type {Post,PostCategory,PostMedia,PostPrivacy} from "@/types/post";
import {safeImageSrc} from "@/lib/media";
type Mode='edit'|'delete'|'report';
export default function PostActionModal({mode,post,content,privacy,onClose,onUpdated,onDeleted,onMessage}:{mode:Mode|null;post:Post;content:string;privacy:PostPrivacy;onClose:()=>void;onUpdated:(post:Post)=>void;onDeleted:()=>void;onMessage:(message:string)=>void}){
 const [text,setText]=useState(content),[visibility,setVisibility]=useState(privacy),[category,setCategory]=useState<PostCategory>(post.category),[media,setMedia]=useState<PostMedia[]>(post.media||[]),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(mode){setText(content);setVisibility(privacy);setCategory(post.category);setMedia(post.media||[]);setReason("");setError("");}},[mode,content,privacy,post.category,post.media]);
 if(!mode)return null;
 const move=(index:number,direction:number)=>setMedia(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const copy=[...current];[copy[index],copy[target]]=[copy[target],copy[index]];return copy;});
 const submit=async()=>{setBusy(true);setError("");try{if(mode==='edit'){if(!text.trim()&&!media.length)throw new Error('Bài viết phải có nội dung hoặc media.');onUpdated(await editPost(post.id,text.trim(),visibility,category,media.map(item=>item.id)));onMessage('Đã cập nhật bài viết.');}else if(mode==='delete'){await deletePost(post.id);onDeleted();}else{if(reason.trim().length<3)throw new Error('Vui lòng nhập lý do rõ ràng.');await createReport('POST',post.id,reason.trim());onMessage('Đã gửi báo cáo tới quản trị viên.');}onClose();}catch(e){setError(e instanceof Error?e.message:'Không thể thực hiện thao tác.');}finally{setBusy(false);}};
 return <div className="post-action-overlay" role="dialog" aria-modal="true" onClick={onClose}><section className="post-action-modal" onClick={e=>e.stopPropagation()}><header><div><small>QUẢN LÝ BÀI VIẾT</small><h2>{mode==='edit'?'Chỉnh sửa bài viết':mode==='delete'?'Xóa bài viết':'Báo cáo bài viết'}</h2></div><button onClick={onClose}>×</button></header><div className="post-action-content">
 {mode==='edit'&&<><label>Nội dung<textarea value={text} onChange={e=>setText(e.target.value)} rows={5}/></label><div className="post-action-fields"><label>Quyền riêng tư<select value={visibility} onChange={e=>setVisibility(e.target.value as PostPrivacy)}><option value="public">Công khai</option><option value="friends">Bạn bè</option><option value="private">Chỉ mình tôi</option></select></label><label>Chuyên mục<select value={category} onChange={e=>setCategory(e.target.value as PostCategory)}><option value="general">Bài chung</option><option value="market">Pass đồ</option><option value="roommate">Phòng trọ</option><option value="event">Sự kiện</option><option value="study">Học tập</option></select></label></div>{media.length>0&&<div className="edit-media-list"><b>Media trong bài</b>{media.map((item,index)=><article key={item.id}>{item.type==='image'?<img src={safeImageSrc(item.url)} alt=""/>:<span>{item.type==='video'?'Video':'Âm thanh'}</span>}<div><button onClick={()=>move(index,-1)} disabled={index===0}>←</button><button onClick={()=>move(index,1)} disabled={index===media.length-1}>→</button><button className="danger" onClick={()=>setMedia(current=>current.filter(x=>x.id!==item.id))}>Gỡ</button></div></article>)}</div>}</>}
 {mode==='delete'&&<div className="post-delete-warning"><strong>Bài viết sẽ bị xóa khỏi bảng tin.</strong><p>Thao tác này không thể hoàn tác.</p></div>}{mode==='report'&&<label>Lý do báo cáo<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={5} placeholder="Mô tả nội dung vi phạm..."/></label>}{error&&<div className="post-error-banner">{error}</div>}</div><footer><button className="btn btn-secondary" onClick={onClose}>Hủy</button><button className={mode==='delete'?'btn btn-danger':'btn btn-primary'} disabled={busy||(mode==='edit'&&!text.trim()&&!media.length)||(mode==='report'&&reason.trim().length<3)} onClick={()=>void submit()}>{busy?'Đang xử lý...':mode==='edit'?'Lưu thay đổi':mode==='delete'?'Xóa bài viết':'Gửi báo cáo'}</button></footer></section></div>;
}
