"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import PostCard from "@/components/post/PostCard";
import ReportQueue from "@/components/admin/ReportQueue";
import {decideGroupJoin,fetchGroupJoinRequests,fetchGroupMembers,fetchGroupPosts,fetchGroups,fetchPendingGroupPosts,kickGroupMember,moderateGroupPost,removeApprovedGroupPost,setGroupPostPinned} from "@/lib/api";
import {getAuthUser} from "@/lib/auth";
import type {ApiGroup,GroupJoinRequest,GroupMember,GroupPost} from "@/types/group-api";
import {useDialog} from "@/components/ui/DialogProvider";
import RelativeTime from "@/components/ui/RelativeTime";

type Tab="overview"|"pending"|"posts"|"members"|"reports";
export default function GroupAdminPage(){
 const dialog=useDialog();
 const [groups,setGroups]=useState<ApiGroup[]>([]),[groupId,setGroupId]=useState(""),[pending,setPending]=useState<GroupPost[]>([]),[posts,setPosts]=useState<GroupPost[]>([]),[joins,setJoins]=useState<GroupJoinRequest[]>([]),[members,setMembers]=useState<GroupMember[]>([]),[tab,setTab]=useState<Tab>("overview"),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const active=groups.find(g=>g.id===groupId);
 const loadGroups=useCallback(async()=>{const auth=getAuthUser(),all=await fetchGroups();const scoped=auth?.system_role==='SUPER_ADMIN'?all:all.filter(g=>auth?.admin_group_slugs?.includes(g.slug));setGroups(scoped);setGroupId(v=>v||scoped[0]?.id||"");},[]);
 const load=useCallback(async()=>{if(!groupId)return;const [waiting,approved,requests,people]=await Promise.all([fetchPendingGroupPosts(groupId),fetchGroupPosts(groupId),fetchGroupJoinRequests(groupId),fetchGroupMembers(groupId,query)]);setPending(waiting);setPosts(approved);setJoins(requests);setMembers(people);},[groupId,query]);
 useEffect(()=>{void loadGroups().catch(e=>setError(e.message));},[loadGroups]);useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
 const act=async(work:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await work();await load();await loadGroups();}catch(e){setError(e instanceof Error?e.message:"Không thể thực hiện thao tác.");}finally{setBusy(false);}};
 const removePost=async(post:GroupPost)=>{const reason=await dialog.prompt({title:'Gỡ bài đã duyệt',message:'Tác giả sẽ nhận được lý do gỡ bài.',placeholder:'Nhập lý do gỡ bài...',multiline:true,minLength:3,tone:'danger'});if(reason)await act(()=>removeApprovedGroupPost(groupId,post.id,reason));};
 const rejectPost=async(post:GroupPost)=>{const reason=await dialog.prompt({title:'Từ chối bài viết',message:`Nêu lý do để ${post.author.name} biết cách chỉnh sửa.`,placeholder:'Lý do từ chối...',multiline:true,minLength:3,tone:'danger'});if(reason)await act(()=>moderateGroupPost(groupId,post.id,'REJECT',reason));};
 const kickMember=async(member:GroupMember)=>{if(await dialog.confirm({title:'Mời thành viên khỏi nhóm?',message:`${member.name} sẽ mất quyền truy cập nội dung dành cho thành viên.`,confirmLabel:'Mời khỏi nhóm',tone:'danger'}))await act(()=>kickGroupMember(groupId,member.id));};
 const stats=useMemo(()=>[{label:"Chờ duyệt",value:pending.length},{label:"Yêu cầu gia nhập",value:joins.length},{label:"Thành viên",value:active?.member_count||members.length},{label:"Bài đang hiển thị",value:posts.length}],[pending.length,joins.length,active,members.length,posts.length]);
 if(!groups.length&&!error)return <main className="group-admin-page"><div className="group-admin-empty"><h1>Không có nhóm được phân công</h1><p>Super Admin cần gán bạn làm Admin của ít nhất một nhóm.</p></div></main>;
 return <main className="group-admin-page"><header className="group-admin-hero"><div><span>GROUP ADMIN WORKSPACE</span><h1>Quản trị nhóm</h1><p>Mọi dữ liệu và thao tác đều giới hạn trong nhóm được phân công.</p></div><select value={groupId} onChange={e=>{setGroupId(e.target.value);setTab("overview");}}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></header>
 {error&&<div className="group-admin-error">{error}</div>}
 <section className="group-admin-stats">{stats.map(s=><article key={s.label}><b>{s.value}</b><span>{s.label}</span></article>)}</section>
 <nav className="group-admin-nav">{([['overview','Tổng quan'],['pending',`Kiểm duyệt (${pending.length})`],['posts','Bài đã duyệt'],['members',`Thành viên (${members.length})`],['reports','Báo cáo']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='overview'&&<section className="group-admin-panel"><h2>Công việc cần xử lý</h2><div className="admin-task-grid"><button onClick={()=>setTab('pending')}><b>{pending.length}</b><span>Bài đang chờ quyết định</span></button><button onClick={()=>setTab('members')}><b>{joins.length}</b><span>Yêu cầu tham gia mới</span></button><button onClick={()=>setTab('reports')}><b>→</b><span>Mở hàng chờ báo cáo</span></button></div></section>}
 {tab==='pending'&&<section className="group-admin-panel"><h2>Hàng chờ kiểm duyệt</h2>{pending.map(p=><article className="moderation-row" key={p.id}><div><strong>{p.author.name}</strong><p>{p.content||"Bài viết chỉ có tệp đính kèm"}</p><RelativeTime value={p.createdAt}/></div><div><button disabled={busy} onClick={()=>act(()=>moderateGroupPost(groupId,p.id,'APPROVE'))}>Phê duyệt</button><button disabled={busy} className="danger" onClick={()=>{void rejectPost(p);}}>Từ chối</button></div></article>)}{!pending.length&&<p className="admin-empty-state">Không có bài chờ duyệt.</p>}</section>}
 {tab==='posts'&&<section className="group-admin-panel"><h2>Bài viết đang hiển thị</h2>{posts.map(p=><div className="managed-post" key={p.id}><PostCard post={p} moderatorGroupId={groupId}/><div><button onClick={()=>act(()=>setGroupPostPinned(groupId,p.id,!p.isPinned))}>{p.isPinned?'Bỏ ghim':'Ghim bài'}</button><button className="danger" onClick={()=>removePost(p)}>Gỡ bài</button></div></div>)}{!posts.length&&<p className="admin-empty-state">Nhóm chưa có bài đã duyệt.</p>}</section>}
 {tab==='members'&&<section className="group-admin-panel"><div className="panel-title-row"><h2>Thành viên và yêu cầu gia nhập</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm theo tên hoặc mã sinh viên"/></div>{joins.map(r=><article className="moderation-row join" key={r.id}><div><strong>{r.name}</strong><p>@{r.username}</p></div><div><button onClick={()=>act(()=>decideGroupJoin(groupId,r.id,'APPROVE'))}>Chấp nhận</button><button className="danger" onClick={()=>act(()=>decideGroupJoin(groupId,r.id,'REJECT'))}>Từ chối</button></div></article>)}<div className="member-table">{members.map(m=><article key={m.id}><div><strong>{m.name}</strong><span>@{m.username} · {m.student_code||'Chưa có MSSV'}</span></div><b>{m.role}</b>{m.role==='MEMBER'&&<button className="danger" onClick={()=>void kickMember(m)}>Mời khỏi nhóm</button>}</article>)}</div>{!members.length&&<p className="admin-empty-state">Không tìm thấy thành viên.</p>}</section>}
 {tab==='reports'&&groupId&&<ReportQueue groupId={groupId}/>}</main>;
}
